name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk
      JAVA_HOME: /usr/lib/jvm/java-11-openjdk-amd64

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Android SDK and Build Tools
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip sdk.zip -d tools
          rm sdk.zip
          yes | tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} --licenses
          tools/bin/sdkmanager --sdk_root=${ANDROID_HOME} \
            "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;21.4.7075529"

      - name: Set Environment Variables
        run: |
          echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$ANDROID_HOME/ndk/21.4.7075529" >> $GITHUB_ENV
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_HOME/emulator" >> $GITHUB_PATH
          echo "$ANDROID_HOME/cmdline-tools/tools/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/build-tools/33.0.2" >> $GITHUB_PATH

      - name: Install Haxe 4.3.6
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6

      - name: Install HMM and Libraries
        run: |
          haxelib --global install hmm
          haxelib --global run hmm setup
          hmm install

      - name: Setup Lime and Android
        run: |
          haxelib run lime setup -y
          haxelib run lime setup android -y

      - name: Build 32-bit APK
        run: |
          haxelib run lime build android -release -Dandroid-arch=armeabi-v7a
          mv export/android/bin/app-release.apk Build32.apk

      - name: Build 64-bit APK
        run: |
          haxelib run lime build android -release -Dandroid-arch=arm64-v8a
          mv export/android/bin/app-release.apk Build64.apk

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: comp-apks
          path: |
            Build32.apk
            Build64.apk
