name: Build Android APKs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Haxe 4.3.6
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.6
          
      - name: Install haxelib 4.2.0
        run: |
          haxelib --global update haxelib
      
      - name: Install Java, Android SDK, and NDK
        uses: android-actions/setup-android@v2
        with:
          sdk-platforms: 'platforms;android-33'
          build-tools: 'build-tools;33.0.2'
          ndk-version: 25.2.9519653

      - name: Set environment variables
        run: |
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$ANDROID_NDK_ROOT" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$ANDROID_NDK_ROOT" >> $GITHUB_ENV

      - name: Install HMM and dependencies
        run: |
          haxelib --global install hmm
          haxelib run hmm setup
          hmm install

      - name: Setup Lime
        run: |
          haxelib run lime setup android

      - name: Build 32-bit APK
        run: |
          haxelib run lime build android -release -Dandroid-arch=armeabi-v7a
          mv export/release/android/bin/app-release.apk Build32.apk

      - name: Build 64-bit APK
        run: |
          haxelib run lime build android -release -Dandroid-arch=arm64-v8a
          mv export/release/android/bin/app-release.apk Build64.apk

      - name: Zip APKs
        run: |
          zip -r comp-apks.zip Build32.apk Build64.apk

      - name: Upload APKs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: comp-apks.zip
          path: comp-apks.zip
